modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="laji"
version="1.0.0"
displayName="Laji"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Feipi"
description='''
More swords
'''

[[dependencies.laji]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




